name: ausweisapp2-ce
version: '1.16.1'
base: core18
summary: AusweisApp2-CE - Tool for the german nPA (Community Edition)
description: |
  The AusweisApp2 (since November 2014 successor of the AusweisApp) is a free application software for the PC to use electronic authentication via the Internet with the new German identity card and the electronic residence permit or their online identification function. This makes it possible for citizens in Germany to identify themselves easily and securely on the Internet - for example, to deal with administrative formalities online.

  The software establishes an encrypted connection between the identity card or the electronic residence permit, the card reader and the eID server on the other side. The IDApp2 serves to securely perform the procedure of certificate and authenticity checks and to offer the  citizen an interface for using the online ID function.

  http://www.ausweisapp.bund.de

architectures: 
  - amd64

icon: snap/gui/icon.svg

grade: stable
confinement: strict


plugs: # additional plugs to pick up the GTK theme and icons from the system
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes


environment:
  QT_QPA_PLATFORMTHEME: gnome # set default theme to gtk to integrate with system theme (GTK3)


apps:
  pcscd:
    command: usr/sbin/pcscd --foreground --auto-exit
    daemon: simple
    plugs:
      - hardware-observe
      - network
      - network-bind
      - raw-usb

  ausweisapp2-ce:
    command: desktop-launch $SNAP/usr/bin/AusweisApp2
    desktop: usr/share/applications/AusweisApp2.desktop
    environment:
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gnome
    plugs:
      - desktop
      - unity7
      - network
      - network-bind
      - home
      - opengl
      - hardware-observe
      - network-manager
      - network-observe


parts:
  pcsc-lite:
    plugin: autotools
    configflags:
      - --prefix=/snap/ausweisapp2-ce/current/usr
      - --enable-usbdropdir=/snap/ausweisapp2-ce/current/usr/lib/pcsc/drivers
      - --enable-ipcdir=/run/snap.ausweisapp2-ce
    source-type: tar
    source: https://pcsclite.apdu.fr/files/pcsc-lite-1.8.24.tar.bz2
    build-packages:
      - gcc
      - pkg-config
      - libsystemd-dev
      - libudev-dev
    override-build: |
        snapcraftctl build
        cp -r ${SNAPCRAFT_PART_INSTALL}/snap/ausweisapp2-ce/current/usr ${SNAPCRAFT_PART_INSTALL}/
        rm -r ${SNAPCRAFT_PART_INSTALL}/snap ${SNAPCRAFT_PART_INSTALL}/lib
        sed -i -e 's/\/snap\/ausweisapp2-ce\/current//g' ${SNAPCRAFT_PART_INSTALL}/usr/lib/pkgconfig/libpcsclite.pc

  
  ccid:
    plugin: autotools
    source-type: tar
    configflags:
      - --prefix=/usr
      - --enable-usbdropdir=/snap/ausweisapp2-ce/current/usr/lib/pcsc/drivers
    source: https://ccid.apdu.fr/files/ccid-1.4.30.tar.bz2
    build-packages:
      - pkg-config
      - libusb-1.0-0-dev
    override-build: |
        snapcraftctl build
        cp -r ${SNAPCRAFT_PART_INSTALL}/snap/ausweisapp2-ce/current/usr ${SNAPCRAFT_PART_INSTALL}/
        rm -r ${SNAPCRAFT_PART_INSTALL}/snap
    stage-packages:
      - libusb-1.0-0 
    after: [pcsc-lite]


  qt5:
    plugin: nil
    prime: [-*]
    override-build: |
      echo "deb http://archive.neon.kde.org/user bionic main" | tee /etc/apt/sources.list.d/kde-neon.list
      wget -O - https://archive.neon.kde.org/public.key | apt-key add - 
      apt update
      apt install -yy qtbase5-dev libqt5websockets5-dev qtconnectivity5-dev qtdeclarative5-dev qtquickcontrols2-5-dev libssl-dev libpcsclite-dev libqt5svg5 libqt5websockets5 libqt5xml5
    build-packages:
      - wget


  desktop-qt5:
    build-packages:
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    after: [qt5]
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5


  qgnomeplatform:
    source: https://github.com/FedoraQt/QGnomePlatform.git
    plugin: qmake
    qt-version: qt5
    build-packages:
      - qtbase5-dev
      - qtbase5-private-dev
      - libgtk-3-dev
    stage-packages:
      - libgtk-3-0
    after: [desktop-qt5]


  patches:
      source: patches
      plugin: dump
      prime: [-*]


  ausweisapp2:
      plugin: cmake
      configflags: [-DCMAKE_BUILD_TYPE=RELEASE, -DCMAKE_INSTALL_PREFIX=/usr/]
      source-type: tar
      source: https://github.com/Governikus/AusweisApp2/releases/download/1.16.1/AusweisApp2-1.16.1.tar.gz
      build-packages:
        - cmake
        - file
        - pkg-config
        - g++
        - qtbase5-dev
        - libqt5svg5-dev
        - qttools5-dev
        - libqt5websockets5-dev
        - qtconnectivity5-dev
        - qtdeclarative5-dev
        - qtquickcontrols2-5-dev
        - libssl-dev
        - libpcsclite-dev
        - libudev-dev
        - libhttp-parser-dev
      stage-packages:
        - libqt5svg5
        - libqt5websockets5
        - libqt5xml5
        - libhttp-parser-dev
        - qtwayland5
        - qt5-style-plugins
      after: [desktop-qt5, qt5, patches]

      override-pull: |
        snapcraftctl pull
        patch -p1 < "${SNAPCRAFT_STAGE}/AusweisApp2-snapcraft.patch"

      override-build: |
        snapcraftctl build
        rm ${SNAPCRAFT_PART_INSTALL}/usr/bin/X11 ${SNAPCRAFT_PART_INSTALL}/usr/bin/fc* ${SNAPCRAFT_PART_INSTALL}/usr/bin/lib* ${SNAPCRAFT_PART_INSTALL}/usr/bin/uc* ${SNAPCRAFT_PART_INSTALL}/usr/bin/lcf
        strip ${SNAPCRAFT_PART_INSTALL}/usr/bin/AusweisApp2
